### ISSUE TITLE
read me update

### ISSUE THREAD

**Issue by samuelwondimu** [henriqpohl/turborepo-tailwindcss-shadcn-ui#3]
i have another three nextjs apps i need to install inside the turb repo how can i achieve that?

the readme file needs to inculde how to add other apps inside the turbrepo

thanks

**Comment by henriqpohl** [comment]
Hi @samuelwondimu, how are you? Hope you're doing well!

I read your email and now I'm reading here, I'm happy that you like the **turborepo-shadcn-ui-tailwindcss** repository and I hope this be useful for you.

About your doubt, you can easily install your NextJS app into the **turborepo-shadcn-ui-tailwindcss** repository, I will you help you with this, take a look below.

To begin, all your NextJS apps should be paste into the **/apps** folder and all your components go into the **/packages/ui/src/components/ui/** (remember, if you have the same components, only paste one, because you can use as shared after) now you got a complete bare bones using **turborepo-shadcn-ui-tailwindcss** repository, the next step is to go to the root directory and run **`pnpm install`** and **`pnpm dev`**.

**Note**: If you have a specific dependences for each App you can add it on their **package.json** individually.

Let me know if you need more help, ok?

Cheers!
